function [runs start params tests] = backpropagation()

    runs = 3;

    start = 1000;

    params = struct( ...
        'maxGenerations', 20, ...
        'pMutateStar', 0.001, ...
        'pCross', 0.75, ...
        'p', 0.05, ...
        'c', 0.95, ...
        'N', 30, ...
        'G', 0.8, ...
        'nonUniformMutation', true, ...
        'replacement', @algorithm.ga.replacement.first, ...
        'selection', @algorithm.ga.selection.elite, ...
        'selection2', @algorithm.ga.selection.roulette, ...
        'crossover', @algorithm.ga.crossover.annular, ...
        'mutation', @algorithm.ga.mutation.locus ...
    );

    tests = {
        struct('name', 'no backpropagation', 'pBack', 0),
        struct('name', 'backpropagation', 'pBack', 0.1)
    };
end

