function [runs start params tests] = backpropagation()

    runs = 3;

    start = 1900;

    params = struct( ...
        'maxGenerations', 20, ...
        'pMutate', 0.0001, ...
        'pCross', 0.9, ...
        'p', 0.05, ...
        'c', 0.95, ...
        'N', 50, ...
        'G', 0.95, ...
        'nonUniformMutation', true, ...
        'replacement', @algorithm.ga.replacement.third, ...
        'selection', @algorithm.ga.selection.roulette, ...
        'selection2', @algorithm.ga.selection.roulette, ...
        'crossover', @algorithm.ga.crossover.annular, ...
        'mutation', @algorithm.ga.mutation.locus, ...
        'changeRatio', 0.95 ...
    );

    tests = {
        struct('name', 'no backprop', 'pBack', 0)
    };
end

