function [runs start params tests] = crossover()

    runs = 6;

    start = 800;

    params = struct( ...
        'maxGenerations', 20, ...
        'pMutateStar', 0.1, ...
        'pBack', 0.1, ...
        'pCross', 0.75, ...
        'p', 0.05, ...
        'c', 0.95, ...
        'N', 30, ...
        'G', 0.9, ...
        'nonUniformMutation', true, ...
        'mutation', @algorithm.ga.mutation.chromosome, ...
        'replacement', @algorithm.ga.replacement.first, ...
        'selection', @algorithm.ga.selection.elite, ...
        'selection2', @algorithm.ga.selection.roulette ...
    );

    tests = {
        struct('name', 'annular'    , 'crossover', @algorithm.ga.crossover.annular),
        struct('name', 'doublePoint', 'crossover', @algorithm.ga.crossover.doublePoint),
        struct('name', 'singlePoint', 'crossover', @algorithm.ga.crossover.singlePoint),
        struct('name', 'uniform'    , 'crossover', @algorithm.ga.crossover.uniform)
    };
end

