function [runs start params tests] = G09()

    runs = 3;

    start = 450;

    params = struct( ...
        'maxGenerations', 20, ...
        'pMutateStar', 0.001, ...
        'pBack', 0.1, ...
        'pCross', 0.75, ...
        'p', 0.05, ...
        'c', 0.95, ...
        'N', 30, ...
        'G', 0.9, ...
        'nonUniformMutation', true, ...
        'crossover', @algorithm.ga.crossover.annular, ...
        'mutation', @algorithm.ga.mutation.locus ...
    );

    tests = {
        struct('name', 'r1-boltz-mix2(G=.9)', 'replacement', @algorithm.ga.replacement.first, 'selection', @algorithm.ga.selection.boltzmann, 'selection2', @algorithm.ga.selection.mixed2),
        struct('name', 'r1-elite-univ(G=.9)', 'replacement', @algorithm.ga.replacement.first, 'selection', @algorithm.ga.selection.elite, 'selection2', @algorithm.ga.selection.universal),
        struct('name', 'r1-elite-roule(G=.9)', 'replacement', @algorithm.ga.replacement.first, 'selection', @algorithm.ga.selection.elite, 'selection2', @algorithm.ga.selection.roulette),
        struct('name', 'r2-boltz-roule(G=.9)', 'replacement', @algorithm.ga.replacement.second, 'selection', @algorithm.ga.selection.boltzmann, 'selection2', @algorithm.ga.selection.roulette),
        struct('name', 'r2-mix2-roule(G=.9)', 'replacement', @algorithm.ga.replacement.second, 'selection', @algorithm.ga.selection.mixed2, 'selection2', @algorithm.ga.selection.roulette)
    };
end

