function [runs start params tests] = replacement_1()

    runs = 3;

    start = 100;

    params = struct( ...
        'maxGenerations', 20, ...
        'pMutateStar', 0.1, ...
        'pBack', 0.1, ...
        'pCross', 0.75, ...
        'p', 0.05, ...
        'c', 0.95, ...
        'N', 30, ...
        'G', 0.9, ...
        'nonUniformMutation', true, ...
        'crossover', @algorithm.ga.crossover.annular, ...
        'mutation', @algorithm.ga.mutation.chromosome, ...
        'replacement', @algorithm.ga.replacement.first ...
    );

    tests = {
        % struct('name', 'r1-elite-mix2', 'selection', @algorithm.ga.selection.elite, 'selection2', @algorithm.ga.selection.mixed2),
        struct('name', 'r1-boltz-mix2', 'selection', @algorithm.ga.selection.boltzmann, 'selection2', @algorithm.ga.selection.mixed2),
        struct('name', 'r1-mix2-mix2', 'selection', @algorithm.ga.selection.mixed2, 'selection2', @algorithm.ga.selection.mixed2),
        % struct('name', 'r1-elite-roule', 'selection', @algorithm.ga.selection.elite, 'selection2', @algorithm.ga.selection.roulette),
        % struct('name', 'r1-boltz-roule', 'selection', @algorithm.ga.selection.boltzmann, 'selection2', @algorithm.ga.selection.roulette),
        % struct('name', 'r1-mix2-roule', 'selection', @algorithm.ga.selection.mixed2, 'selection2', @algorithm.ga.selection.roulette),
        % struct('name', 'r1-elite-univ', 'selection', @algorithm.ga.selection.elite, 'selection2', @algorithm.ga.selection.universal),
        struct('name', 'r1-boltz-univ', 'selection', @algorithm.ga.selection.boltzmann, 'selection2', @algorithm.ga.selection.universal),
        struct('name', 'r1-mix2-univ', 'selection', @algorithm.ga.selection.mixed2, 'selection2', @algorithm.ga.selection.universal)
    };
end

