runs = 3;

start = 500;

params = struct( ...
    'maxGenerations', 20, ...
    'pMutateStar', 0.1, ...
    'pBack', 0.1, ...
    'pCross', 0.75, ...
    'p', 0.05, ...
    'c', 0.95, ...
    'N', 30, ...
    'nonUniformMutation', true, ...
    'crossover', @algorithm.ga.crossover.annular, ...
    'mutation', @algorithm.ga.mutation.chromosome, ...
    'replacement', @algorithm.ga.replacement.first ...
);

tests = {
    struct('selection', @algorithm.ga.selection.elite),
    struct('selection', @algorithm.ga.selection.roulette),
    struct('selection', @algorithm.ga.selection.tourney),
    struct('selection', @algorithm.ga.selection.rank),
    struct('selection', @algorithm.ga.selection.boltzman, 'tempFactor', 1),
    struct('selection', @algorithm.ga.selection.boltzman, 'tempFactor', 0.5),
    struct('selection', @algorithm.ga.selection.boltzman, 'tempFactor', 0.1),
    struct('selection', @algorithm.ga.selection.universal),
    struct('selection', @algorithm.ga.selection.mixed1, 'a', 0.1),
    struct('selection', @algorithm.ga.selection.mixed1, 'a', 0.2),
    struct('selection', @algorithm.ga.selection.mixed2, 'a', 0.1),
    struct('selection', @algorithm.ga.selection.mixed2, 'a', 0.2)
};

runTests(runs, start, params, tests);

